import mongoose from "mongoose";
import bcrypt from "bcrypt";
import dotenv from "dotenv";
import User from "../models/User.js";
import dns from "dns";

dns.setServers(["1.1.1.1", "8.8.8.8"]);
dotenv.config();

const defaultPassword = await bcrypt.hash("Lawyer@123", 10);

const lawyers = [

  // ── Hyderabad ──────────────────────────────────────────────
  {
    name: "Venkat Ramaiah Choudary",
    email: "venkat.ramaiah@advocate.telangana.in",
    district: "Hyderabad",
    specialization: "Criminal Law",
    experience: 18,
    barCouncilNumber: "TS/0124/2006",
    languages: ["Telugu", "English", "Hindi"],
    consultationFee: 0,
    availability: "available",
    bio: "Senior criminal defense attorney with 18 years of experience in Telangana High Court. Specialized in bail applications, criminal appeals and sessions court trials.",
    phone: "9848012345",
    education: ["LLB - Osmania University", "LLM - NALSAR University of Law"],
    courtsPracticing: ["Telangana High Court", "City Sessions Court Hyderabad"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Sunitha Reddy Mallela",
    email: "sunitha.reddy@advocate.telangana.in",
    district: "Hyderabad",
    specialization: "Family Law",
    experience: 12,
    barCouncilNumber: "TS/0456/2012",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Experienced family law practitioner handling divorce, child custody, maintenance and domestic violence cases. Strong advocate for women's rights.",
    phone: "9848023456",
    education: ["LLB - University College of Law Hyderabad", "Diploma in Family Law"],
    courtsPracticing: ["Family Court Hyderabad", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Mohammed Aslam Khan",
    email: "aslam.khan@advocate.telangana.in",
    district: "Hyderabad",
    specialization: "Property Law",
    experience: 22,
    barCouncilNumber: "TS/0789/2002",
    languages: ["Telugu", "Urdu", "English", "Hindi"],
    consultationFee: 0,
    availability: "available",
    bio: "Expert in property disputes, land acquisition matters, mutation cases and GHMC related issues. Practiced for over two decades in Hyderabad courts.",
    phone: "9848034567",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["City Civil Court Hyderabad", "Telangana High Court", "MACT Court"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Padmavathi Srinivas",
    email: "padmavathi.srinivas@advocate.telangana.in",
    district: "Hyderabad",
    specialization: "Labour Law",
    experience: 9,
    barCouncilNumber: "TS/1023/2015",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Dedicated labour law advocate helping workers with wrongful termination, ESI, PF disputes and industrial tribunal matters.",
    phone: "9848045678",
    education: ["LLB - Kakatiya University", "LLM - Osmania University"],
    courtsPracticing: ["Labour Court Hyderabad", "Industrial Tribunal Hyderabad"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Rajesh Kumar Gupta",
    email: "rajesh.gupta@advocate.telangana.in",
    district: "Hyderabad",
    specialization: "Consumer Law",
    experience: 7,
    barCouncilNumber: "TS/1456/2017",
    languages: ["Telugu", "Hindi", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Consumer rights advocate with expertise in DCDRC cases, insurance disputes and e-commerce fraud cases.",
    phone: "9848056789",
    education: ["LLB - Symbiosis Law School"],
    courtsPracticing: ["District Consumer Disputes Redressal Commission Hyderabad"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Rangareddy ─────────────────────────────────────────────
  {
    name: "Naresh Babu Kommula",
    email: "naresh.kommula@advocate.telangana.in",
    district: "Rangareddy",
    specialization: "Criminal Law",
    experience: 14,
    barCouncilNumber: "TS/1789/2010",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Criminal law specialist with extensive experience in Sessions Court, Rangareddy. Handles POCSO cases, dowry cases and murder trials.",
    phone: "9848067890",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["Sessions Court Rangareddy", "Magistrate Court Rangareddy"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Kavitha Devi Namburi",
    email: "kavitha.namburi@advocate.telangana.in",
    district: "Rangareddy",
    specialization: "Civil Law",
    experience: 11,
    barCouncilNumber: "TS/2012/2013",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Civil litigation expert handling land disputes, injunctions, partition suits and recovery cases in Rangareddy district courts.",
    phone: "9848078901",
    education: ["LLB - University College of Law", "LLM - Osmania University"],
    courtsPracticing: ["Civil Court Rangareddy", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Warangal Urban ─────────────────────────────────────────
  {
    name: "Suresh Chandra Yadav",
    email: "suresh.yadav@advocate.telangana.in",
    district: "Warangal Urban",
    specialization: "Criminal Law",
    experience: 16,
    barCouncilNumber: "TS/2345/2008",
    languages: ["Telugu", "Hindi", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Senior criminal lawyer based in Warangal with expertise in High Court bail matters, criminal revisions and anticipatory bail.",
    phone: "9848089012",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Sessions Court Warangal", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Anitha Laxmi Potharaju",
    email: "anitha.potharaju@advocate.telangana.in",
    district: "Warangal Urban",
    specialization: "Family Law",
    experience: 8,
    barCouncilNumber: "TS/2678/2016",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Family court specialist in Warangal handling divorce, maintenance, child custody and domestic violence protection orders.",
    phone: "9848090123",
    education: ["LLB - Kakatiya University", "Diploma in Women's Rights Law"],
    courtsPracticing: ["Family Court Warangal", "Magistrate Court Warangal"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Ravi Shankar Teja",
    email: "ravi.teja@advocate.telangana.in",
    district: "Warangal Urban",
    specialization: "Property Law",
    experience: 13,
    barCouncilNumber: "TS/2901/2011",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Property law expert handling land ceiling cases, mutation disputes and pattadar passbook issues in Warangal and surrounding areas.",
    phone: "9848001234",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Civil Court Warangal", "Revenue Court Warangal"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Karimnagar ─────────────────────────────────────────────
  {
    name: "Srinivas Rao Gundepally",
    email: "srinivas.gundepally@advocate.telangana.in",
    district: "Karimnagar",
    specialization: "Civil Law",
    experience: 20,
    barCouncilNumber: "TS/3234/2004",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Veteran civil lawyer with 20 years of practice in Karimnagar courts. Handles land acquisition, injunctions and civil appeals.",
    phone: "9848112345",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["District Court Karimnagar", "Civil Court Karimnagar"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Madhavi Latha Errabelly",
    email: "madhavi.errabelly@advocate.telangana.in",
    district: "Karimnagar",
    specialization: "Constitutional Law",
    experience: 10,
    barCouncilNumber: "TS/3567/2014",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Constitutional law advocate focusing on fundamental rights, PIL matters and writ petitions before Telangana High Court.",
    phone: "9848123456",
    education: ["LLB - NALSAR University of Law", "LLM - Constitutional Law"],
    courtsPracticing: ["Telangana High Court", "District Court Karimnagar"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Nizamabad ──────────────────────────────────────────────
  {
    name: "Abdul Raheem Syed",
    email: "abdul.raheem@advocate.telangana.in",
    district: "Nizamabad",
    specialization: "Criminal Law",
    experience: 15,
    barCouncilNumber: "TS/3890/2009",
    languages: ["Telugu", "Urdu", "English", "Hindi"],
    consultationFee: 0,
    availability: "available",
    bio: "Criminal defense specialist in Nizamabad with expertise in SC/ST atrocity cases, NDPS matters and bail proceedings.",
    phone: "9848134567",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["Sessions Court Nizamabad", "Magistrate Courts Nizamabad"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Rekha Venugopal",
    email: "rekha.venugopal@advocate.telangana.in",
    district: "Nizamabad",
    specialization: "Family Law",
    experience: 6,
    barCouncilNumber: "TS/4123/2018",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Young and dedicated family law practitioner helping underprivileged women with divorce, maintenance and protection order cases.",
    phone: "9848145678",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Family Court Nizamabad"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Khammam ────────────────────────────────────────────────
  {
    name: "Bhaskar Rao Vemuri",
    email: "bhaskar.vemuri@advocate.telangana.in",
    district: "Khammam",
    specialization: "Labour Law",
    experience: 17,
    barCouncilNumber: "TS/4456/2007",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Labour law veteran in Khammam handling coal mine worker disputes, SCCL related cases, ESI and provident fund matters.",
    phone: "9848156789",
    education: ["LLB - Andhra University", "Diploma in Labour Laws"],
    courtsPracticing: ["Labour Court Khammam", "Industrial Tribunal"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Jyothi Prasad Nelluri",
    email: "jyothi.nelluri@advocate.telangana.in",
    district: "Khammam",
    specialization: "Property Law",
    experience: 11,
    barCouncilNumber: "TS/4789/2013",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Property disputes specialist in Khammam handling tribal land issues, forest rights cases and pattadar matters.",
    phone: "9848167890",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["District Court Khammam", "Civil Court Khammam"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Nalgonda ───────────────────────────────────────────────
  {
    name: "Tirupathi Reddy Banda",
    email: "tirupathi.banda@advocate.telangana.in",
    district: "Nalgonda",
    specialization: "Civil Law",
    experience: 14,
    barCouncilNumber: "TS/5012/2010",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Civil law expert in Nalgonda handling irrigation disputes, land acquisition for projects and revenue court matters.",
    phone: "9848178901",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["District Court Nalgonda", "Revenue Court Nalgonda"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Saraswathi Devi Katta",
    email: "saraswathi.katta@advocate.telangana.in",
    district: "Nalgonda",
    specialization: "Consumer Law",
    experience: 5,
    barCouncilNumber: "TS/5345/2019",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Consumer rights advocate helping citizens with banking fraud, insurance claims and defective product cases in Nalgonda.",
    phone: "9848189012",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["District Consumer Forum Nalgonda"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Medchal-Malkajgiri ─────────────────────────────────────
  {
    name: "Prakash Narayan Iyer",
    email: "prakash.iyer@advocate.telangana.in",
    district: "Medchal-Malkajgiri",
    specialization: "Property Law",
    experience: 19,
    barCouncilNumber: "TS/5678/2005",
    languages: ["Telugu", "Tamil", "English", "Hindi"],
    consultationFee: 0,
    availability: "available",
    bio: "Senior property lawyer specializing in HMDA layout disputes, apartment registration issues and real estate fraud cases in Medchal.",
    phone: "9848190123",
    education: ["LLB - Madras University", "LLM - Osmania University"],
    courtsPracticing: ["Civil Court Medchal", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Vijaya Lakshmi Gorantla",
    email: "vijaya.gorantla@advocate.telangana.in",
    district: "Medchal-Malkajgiri",
    specialization: "Family Law",
    experience: 9,
    barCouncilNumber: "TS/5901/2015",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Family law advocate helping victims of domestic abuse and matrimonial disputes in Medchal-Malkajgiri district.",
    phone: "9848201234",
    education: ["LLB - NALSAR University of Law"],
    courtsPracticing: ["Family Court Malkajgiri", "Magistrate Court Medchal"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Sangareddy ─────────────────────────────────────────────
  {
    name: "Ramesh Goud Patel",
    email: "ramesh.patel@advocate.telangana.in",
    district: "Sangareddy",
    specialization: "Criminal Law",
    experience: 13,
    barCouncilNumber: "TS/6234/2011",
    languages: ["Telugu", "Hindi", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Criminal defense lawyer in Sangareddy with expertise in land grabbing cases, cheque bounce cases and Sessions Court trials.",
    phone: "9848212345",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["Sessions Court Sangareddy", "Magistrate Court Sangareddy"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Lakshmi Prasanna Vanga",
    email: "lakshmi.vanga@advocate.telangana.in",
    district: "Sangareddy",
    specialization: "Labour Law",
    experience: 7,
    barCouncilNumber: "TS/6567/2017",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Labour rights advocate in Sangareddy helping MSME workers, construction labourers and agricultural workers with legal aid.",
    phone: "9848223456",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Labour Court Sangareddy"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Adilabad ───────────────────────────────────────────────
  {
    name: "Venkatesh Atram",
    email: "venkatesh.atram@advocate.telangana.in",
    district: "Adilabad",
    specialization: "Constitutional Law",
    experience: 16,
    barCouncilNumber: "TS/6890/2008",
    languages: ["Telugu", "Marathi", "Hindi", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Constitutional and tribal rights lawyer in Adilabad. Expert in PESA Act, Forest Rights Act and tribal land protection matters.",
    phone: "9848234567",
    education: ["LLB - Nagpur University", "LLM - Constitutional Law"],
    courtsPracticing: ["District Court Adilabad", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Shobha Rani Meshram",
    email: "shobha.meshram@advocate.telangana.in",
    district: "Adilabad",
    specialization: "Family Law",
    experience: 8,
    barCouncilNumber: "TS/7123/2016",
    languages: ["Telugu", "Marathi", "Hindi"],
    consultationFee: 0,
    availability: "available",
    bio: "Family and women's rights lawyer serving tribal communities in Adilabad with free legal aid for domestic violence and maintenance cases.",
    phone: "9848245678",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Family Court Adilabad", "Magistrate Court Adilabad"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Mahbubnagar ────────────────────────────────────────────
  {
    name: "Narayana Reddy Polasa",
    email: "narayana.polasa@advocate.telangana.in",
    district: "Mahabubnagar",
    specialization: "Civil Law",
    experience: 21,
    barCouncilNumber: "TS/7456/2003",
    languages: ["Telugu", "Kannada", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Senior civil lawyer with 21 years of practice in Mahabubnagar. Handles inter-state land disputes, irrigation water disputes and revenue cases.",
    phone: "9848256789",
    education: ["LLB - Bangalore University"],
    courtsPracticing: ["District Court Mahabubnagar", "Revenue Appellate Court"],
    verificationStatus: "approved",
    isVerified: true,
  },
  {
    name: "Padma Sudha Yerragunta",
    email: "padma.yerragunta@advocate.telangana.in",
    district: "Mahabubnagar",
    specialization: "Criminal Law",
    experience: 10,
    barCouncilNumber: "TS/7789/2014",
    languages: ["Telugu", "Kannada", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Criminal advocate specializing in migrant worker rights, bonded labour cases and SC/ST atrocity cases in Mahabubnagar.",
    phone: "9848267890",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["Sessions Court Mahabubnagar"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Siddipet ───────────────────────────────────────────────
  {
    name: "Krishna Murthy Tandur",
    email: "krishna.tandur@advocate.telangana.in",
    district: "Siddipet",
    specialization: "Property Law",
    experience: 12,
    barCouncilNumber: "TS/8012/2012",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Property law expert in Siddipet dealing with Kaleshwaram project land acquisition disputes and farmers' compensation cases.",
    phone: "9848278901",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Civil Court Siddipet", "Revenue Court Siddipet"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Yadadri Bhuvanagiri ────────────────────────────────────
  {
    name: "Shankar Prasad Boini",
    email: "shankar.boini@advocate.telangana.in",
    district: "Yadadri Bhuvanagiri",
    specialization: "Criminal Law",
    experience: 9,
    barCouncilNumber: "TS/8345/2015",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Criminal law practitioner in Yadadri Bhuvanagiri handling temple land encroachment cases, endowment department disputes and criminal trials.",
    phone: "9848289012",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["District Court Yadadri", "Magistrate Court Bhongir"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Suryapet ───────────────────────────────────────────────
  {
    name: "Usha Rani Jonnalagadda",
    email: "usha.jonnalagadda@advocate.telangana.in",
    district: "Suryapet",
    specialization: "Family Law",
    experience: 14,
    barCouncilNumber: "TS/8678/2010",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Experienced family court advocate in Suryapet providing free legal aid to women and children in matrimonial and custody disputes.",
    phone: "9848290123",
    education: ["LLB - Andhra University", "Diploma in Child Rights Law"],
    courtsPracticing: ["Family Court Suryapet", "District Court Suryapet"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Jagtial ────────────────────────────────────────────────
  {
    name: "Mahender Singh Rathod",
    email: "mahender.rathod@advocate.telangana.in",
    district: "Jagtial",
    specialization: "Labour Law",
    experience: 11,
    barCouncilNumber: "TS/9012/2013",
    languages: ["Telugu", "Hindi", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Labour law advocate in Jagtial helping farmers, BPL workers and unorganized sector employees with legal aid for workplace disputes.",
    phone: "9848301234",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Labour Court Jagtial", "Magistrate Court Jagtial"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Mancherial ─────────────────────────────────────────────
  {
    name: "Kishan Rao Deshpande",
    email: "kishan.deshpande@advocate.telangana.in",
    district: "Mancherial",
    specialization: "Constitutional Law",
    experience: 18,
    barCouncilNumber: "TS/9345/2006",
    languages: ["Telugu", "Marathi", "Hindi", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Constitutional lawyer in Mancherial specializing in coal miner rights, environmental law and PIL matters related to industrial pollution.",
    phone: "9848312345",
    education: ["LLB - Nagpur University", "LLM - Environmental Law"],
    courtsPracticing: ["District Court Mancherial", "National Green Tribunal", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Kamareddy ──────────────────────────────────────────────
  {
    name: "Geetha Devi Naik",
    email: "geetha.naik@advocate.telangana.in",
    district: "Kamareddy",
    specialization: "Consumer Law",
    experience: 6,
    barCouncilNumber: "TS/9678/2018",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Consumer rights advocate in Kamareddy fighting against banking fraud, telecom disputes and medical negligence cases for rural citizens.",
    phone: "9848323456",
    education: ["LLB - Osmania University"],
    courtsPracticing: ["District Consumer Forum Kamareddy"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Peddapalli ─────────────────────────────────────────────
  {
    name: "Raju Goud Edula",
    email: "raju.edula@advocate.telangana.in",
    district: "Peddapalli",
    specialization: "Criminal Law",
    experience: 13,
    barCouncilNumber: "TS/9901/2011",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Criminal advocate in Peddapalli with expertise in SCCL worker cases, coal mafia matters and industrial accident compensation.",
    phone: "9848334567",
    education: ["LLB - Kakatiya University"],
    courtsPracticing: ["Sessions Court Peddapalli", "Magistrate Courts Ramagundam"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Nagarkurnool ───────────────────────────────────────────
  {
    name: "Srinivasulu Banoth",
    email: "srinivasulu.banoth@advocate.telangana.in",
    district: "Nagarkurnool",
    specialization: "Constitutional Law",
    experience: 15,
    barCouncilNumber: "TS/0234/2009",
    languages: ["Telugu", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Tribal rights and constitutional law advocate in Nagarkurnool. Expert in Srisailam project displaced families' cases and ST reservation matters.",
    phone: "9848345678",
    education: ["LLB - Osmania University", "LLM - Constitutional Law"],
    courtsPracticing: ["District Court Nagarkurnool", "Telangana High Court"],
    verificationStatus: "approved",
    isVerified: true,
  },

  // ── Medak ──────────────────────────────────────────────────
  {
    name: "Venkataramana Pillai",
    email: "venkataramana.pillai@advocate.telangana.in",
    district: "Medak",
    specialization: "Civil Law",
    experience: 16,
    barCouncilNumber: "TS/0567/2008",
    languages: ["Telugu", "Tamil", "English"],
    consultationFee: 0,
    availability: "available",
    bio: "Civil law practitioner in Medak specializing in tank and irrigation land disputes, gram panchayat matters and civil appeals.",
    phone: "9848356789",
    education: ["LLB - Madras University"],
    courtsPracticing: ["District Court Medak", "Civil Court Medak"],
    verificationStatus: "approved",
    isVerified: true,
  },
];

async function seedLawyers() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");

    let added   = 0;
    let skipped = 0;

    for (const lawyer of lawyers) {
      const existing = await User.findOne({ email: lawyer.email });
      if (existing) {
        console.log(`⏭️  Skipped (already exists): ${lawyer.name}`);
        skipped++;
        continue;
      }

      await User.create({
        ...lawyer,
        password:     defaultPassword,
        role:         "lawyer",
        state:        "Telangana",
        isActive:     true,
        isBanned:     false,
        importedFrom: "seed",
        dataSource:   "Demo Data — Bar Council of Telangana (Sample)",
      });

      console.log(`✅ Added: ${lawyer.name} — ${lawyer.district} — ${lawyer.specialization}`);
      added++;
    }

    console.log("\n═══════════════════════════════════");
    console.log(`✅ Done! Added: ${added} | Skipped: ${skipped}`);
    console.log(`📊 Total lawyers in DB: ${await User.countDocuments({ role: "lawyer" })}`);
    console.log("═══════════════════════════════════");
    process.exit(0);

  } catch (error) {
    console.error("❌ Seed failed:", error.message);
    process.exit(1);
  }
}

seedLawyers();