export const CASE_TYPES = [
  { label: "APPL (APPLICATION IN CIVIL SUIT)", mtype: 1 },
  { label: "ARBAPPL (ARBITRATION APPLICATION)", mtype: 2 },
  { label: "AS (FIRST APPEAL)", mtype: 3 },
  { label: "CA (CONTEMPT APPEAL)", mtype: 4 },
  { label: "CAPPEAL (COMPANY APPEAL)", mtype: 5 },
  { label: "CC (CONTEMPT CASE)", mtype: 6 },
  { label: "CCCA (CITY CIVIL COURT APPEAL)", mtype: 7 },
  { label: "CC(TR) (CONTEMPT CASE TRANSFERED)", mtype: 8 },
  { label: "CEA (CENTRAL EXCISE APPEALS)", mtype: 9 },
  { label: "CERC (CUSTOMS EXCISE REVISION CASE)", mtype: 10 },
  { label: "CETC (CENTRAL EXCISE TAX CASE)", mtype: 11 },
  { label: "CMA (CIVIL MISCELLANEOUS APPEAL)", mtype: 12 },
  { label: "CMSA (CIVIL MISCELLANEOUS SECOND APPEAL)", mtype: 13 },
  { label: "COMCA (COMMERCIAL COURT APPEAL)", mtype: 14 },
  { label: "COMPA (COMPANY APPL. IN COMPANY PETITION)", mtype: 15 },
  { label: "COMS (COMMERCIAL SUIT)", mtype: 16 },
  { label: "COMTA (COMMERCIAL TRANSFER APPLICATION)", mtype: 17 },
  { label: "CP (COMPANY PETITION)", mtype: 18 },
  { label: "CRLA (CRIMINAL APPEAL)", mtype: 19 },
  { label: "CRLP (CRIMINAL PETITION)", mtype: 21 },
  { label: "CRLRC (CRIMINAL REVISION CASE)", mtype: 22 },
  { label: "CRP (CIVIL REVISION PETITION)", mtype: 23 },
  { label: "CS (CIVIL SUIT)", mtype: 24 },
  { label: "EDC (ESTATE DUTY CASE)", mtype: 25 },
  { label: "EP (ELECTION PETITION)", mtype: 26 },
  { label: "EPTC (EXCESS PROFIT TAX CASE)", mtype: 27 },
  { label: "EXEP (EXECUTION PETITION)", mtype: 28 },
  { label: "FCA (FAMILY COURT APPEAL)", mtype: 29 },
  { label: "GTC (GIFT TAX CASE)", mtype: 30 },
  { label: "ITC (INCOME TAX CASE)", mtype: 31 },
  { label: "ITTA (INCOME TAX TRIBUNAL APPEAL)", mtype: 32 },
  { label: "LAAS (LAND ACQUISITION FIRST APPEAL)", mtype: 33 },
  { label: "LGA (LAND GRABBING APPEAL)", mtype: 34 },
  { label: "LPA (LETTER PATENT APPEAL)", mtype: 35 },
  { label: "MACMA (MOTOR ACCIDENT CIVIL MISCELLANEOUS APPEAL)", mtype: 36 },
  { label: "OP (ORIGINAL PETITION)", mtype: 37 },
  { label: "OSA (ORIGINAL SIDE APPEAL)", mtype: 38 },
  { label: "PIL (PUBLIC INTEREST LITIGATION OLD)", mtype: 39 },
  { label: "RC (REFERRED CASE)", mtype: 40 },
  { label: "RCC (REFERRED COMPANY CASE)", mtype: 41 },
  { label: "RECR (RECRIMINATION PETITION)", mtype: 42 },
  { label: "REFCRLA (REFERRED CRLA)", mtype: 43 },
  { label: "RESWPMP(TR) (WPMP TRANSFERRED)", mtype: 44 },
  { label: "REVWP(TR)MP (REVIEW WP(TR))", mtype: 45 },
  { label: "RT (REFERRED TRIAL)", mtype: 46 },
  { label: "RTP (RECEIVE AND TRANSMIT PETITION)", mtype: 48 },
  { label: "SA (SECOND APPEAL)", mtype: 49 },
  { label: "SCLP (SUPREME COURT LEAVE PETITION)", mtype: 50 },
  { label: "SPLA (SPECIAL APPEAL)", mtype: 51 },
  { label: "STA (SPECIAL TRIBUNAL APPEAL)", mtype: 52 },
  { label: "TRAS (TRANSFER APPEAL)", mtype: 53 },
  { label: "TRC (TAX REVISION CASE OLD)", mtype: 54 },
  { label: "TRCCCA (TRANSFER CCCA)", mtype: 55 },
  { label: "TRCMA (TRANSFER CIVIL MISC APPEAL)", mtype: 56 },
  { label: "TRCMP (TRANSFER CIVIL MISC PETITION)", mtype: 57 },
  { label: "TRCRLA (TRANSFER CRIMINAL APPEAL)", mtype: 58 },
  { label: "TRCRLMP (TRANSFER CRIMINAL MISC PETITION)", mtype: 59 },
  { label: "TRCRLP (TRANSFER CRIMINAL PETITION)", mtype: 60 },
  { label: "TREVC (TAX REVISION CASE)", mtype: 61 },
  { label: "WA (WRIT APPEAL)", mtype: 62 },
  { label: "WP (WRIT PETITION)", mtype: 63 },
  { label: "WP(PIL) (PUBLIC INTEREST LITIGATION)", mtype: 64 },
  { label: "WP(TR) (WRIT PETITION TRANSFERED)", mtype: 65 },
  { label: "WTA (WEALTH TAX APPEAL)", mtype: 66 },
  { label: "WTC (WEALTH TAX CASE)", mtype: 67 },

  // newer types
  { label: "COMOP (COMMERCIAL ORIGINAL PETITION)", mtype: 68 },
  { label: "ICOMAOA (INTERNATIONAL COMMERCIAL ARBITRATION ORIGINAL APPLICATION)", mtype: 69 },
  { label: "X-OBJ (CROSS OBJECTION)", mtype: 70 },
  { label: "CRLATR (CRIMINAL APPEAL TRANSFER)", mtype: 72 },
  { label: "TRICOMAOA (TRANSFER INTERNATIONAL COMMERCIAL ARBITRATION ORIGINAL APPLICATION)", mtype: 73 },
  { label: "RESLGAIA (RESTORATION LAND GRABBING APPLICATION)", mtype: 74 },
  { label: "ICOMAA (INTERNATIONAL COMMERCIAL ARBITRATION APPEAL)", mtype: 75 },
  { label: "COMDA (COMMERCIAL APPEAL)", mtype: 76 },
  { label: "COMTOA (TRANSFER APPLICATION BEFORE COMMERCIAL APPELLATE DIVISION)", mtype: 77 },
  { label: "COMAOA (COMMERCIAL ARBITRATION ORIGINAL APPLICATION)", mtype: 78 },
  { label: "COMAA (COMMERCIAL ARBITRATION APPEAL)", mtype: 79 },
  { label: "TRCOS (TRANSFER COMMERCIAL ORIGINAL SUIT)", mtype: 80 },
  { label: "SUOMOTUWPUR (SUOMOTU WRIT PETITION URGENT)", mtype: 81 },
  { label: "TRSUMMARYSUIT (TRANSFER SUMMARY SUIT)", mtype: 82 },
  { label: "TUPWP (TAKEN UP WRIT PETITION)", mtype: 83 },
  { label: "TUPWP(PIL) (TAKEN UP PUBLIC INTEREST LITIGATION)", mtype: 84 },
  { label: "TRLGA (TRANSFER LAND GRABBING APPEAL)", mtype: 85 },
  { label: "CC(CRL) (CRIMINAL CALENDER CASE)", mtype: 86 },
  { label: "SUOMOTUWP (SUOMOTU WRIT PETITION)", mtype: 87 },
  { label: "SUOMOTUWP(PIL) (SUOMOTU WRIT PETITION PUBLIC INTEREST LITIGATION)", mtype: 88 },
  { label: "CRLA(FSSA) (CRIMINAL APPEAL FOOD SAFETY AND STANDARDS ACT)", mtype: 89 },
  { label: "CS(9BY1) (CIVIL SUIT 9BY1)", mtype: 90 },
  { label: "WA X-OBJ (WRIT CROSS OBJECTION)", mtype: 91 },
  { label: "SARERA (SECOND APPEAL RERA)", mtype: 92 },
  { label: "CMARERA (CIVIL MISCELLANEOUS APPEAL RERA)", mtype: 93 },
  { label: "SUOMOTUCC (SUOMOTU CONTEMPT CASES)", mtype: 94 },
];